readLines(con = "German-credit-1.csv" ,n=5)

df<- read.table(file="german-credit-1.csv",header = T , sep = ",")

head(df)
df<- read.csv(file="german-credit-1.csv",header=T)

head(df)
install.packages("XLConnect")
colnames(df)
df1<- read.csv(file="german-credit-2.csv",header=T)
head(df1)
colnames(df1)
df2<-merge(x=df,y=df1,by="OBS",all=T)
head(df2)
tail(df)
summary(df)
str(df)
num_attr<-c("DURATION","AMOUNT","INSTALL_RATE","AGE","NUM_CREDITS","NUM_DEPENDENTS")
cat_attr<-setdiff(x=colnames(df2),y=num_attr)
df2$OBS<-as.character(df2$OBS)
test_vec <- c(0,1,1,1,1,0,0,0,1,0,1,0,1,0)
test_vec
fac_vec<-as.factor(test_vec)
fac_vec
reconverted_vec <- as.numeric(fac_vec)
reconverted_vec
df2$RESPONSE<- as.factor(as.character(df2$RESPONSE))
df_cat <- subset(df2,select = cat_attr)
df2[,cat_attr] <- data.frame(apply(df_cat,2,function(x)as.factor(as.character(x))))
str(df2)
colSums(is.na(x=df2))
sum(is.na(df2))
df3<-na.omit(df2)
dim(df2)
dim(df3)
df3
sum(is.na(df3))
library(DMwR)
install.packages("DMwR")
manyNAs(df2,0.1)
manyNAs(df2, 0.1)
df2_imputed <- centralImputation(data = df2)
sum(is.na(df2_imputed))
df2
#df2_imputed1 <- knnImputation(data = df2,k=5)
#sum(is.na(df3))
install.packages("infotheo")
library(infotheo)
x <- c(5,6,7,8,8,8,8,8,11,20,21,22)
length(x)
x0 <- discretize(x,disc = "equalfreq", nbins = 4)
table(x0)
x1 <- discretize(x,disc = "equalwidth",nbins = 4)
table(x1)
install.packages("dummies")
library(dummies)
df0_ex <-datasets::warpbreaks
table(df0_ex)
